# Example configuration for the santa-sleigh daemon.

[aws]
region = "us-west-2"
bucket = "my-santa-telemetry"
# access_key = "AKIA..."          # Optional: falls back to environment/instance metadata if unset.
# secret_key = "..."               # Optional counterpart for access_key.
# session_token = "..."            # Optional STS session token.
# profile = "sso-profile"          # Optional shared config profile name.
# custom_url = "https://s3.mycompany.local" # Optional for S3-compatible endpoints.
use_path_style = false
key_prefix = "santa/telemetry"

[logging]
level = "info"
file = "/var/log/santa-sleigh/santa-sleigh.log"

[upload]
mode = "parquet"            # "parquet" or "json"
# For parquet mode this is treated as a directory of files to process.
# For json mode this is the file that santa-sleigh tails and rotates.
queue = "/var/lib/santa-sleigh/queue"
concurrency = 4
poll_interval = "15s"
max_retries = 3
staging_suffix = ".partial"
json_max_bytes = 10485760       # 10 MB default
json_max_interval = "5m"       # Rotate at least every 5 minutes
